### PR TITLE
switch-to-configuration: handle /proc and /sys specially

### PR DESCRIPTION
**Pull request by abbradar**
With this fsoptions implementation should work fine.

### CODE REVIEW

**Comment by abbradar** [comment]
Wait a bit, I discovered that this won't work for the first activation. I'll submit updated patch later today.

**Comment by abbradar** [comment]
Done!

**Comment by joachifm** [comment]
Oh, sorry, I had disabled watching on my own nixpkgs repo and so didn't see this before now!

**Comment by joachifm** [comment]
The vm test fails for me, does it work for you?

**Comment by abbradar** [comment]
Ouch, this is because we override `fileSystems` in VMs: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/qemu-vm.nix#L420
This is unfortunate. Of course we can just copy needed `fileSystems` entry to the test but then this won't be the module test -- it would rather test this mount option. I'm unsure what to do...

**Comment by joachifm** [comment]
I would rather go ahead with my original implementation, sure it's a bit ugly, but it will work. This change can still go onto the enable systemd-remount-fs in containers PR or does that whole thing no longer matter, given that the main use-case for enabling it seems to have evaporated?

**Comment by abbradar** [comment]
Hm, I don't see much value in it without this (and some added complexity). Let's go ahead with yours, then -- at least it works indeed!

**Comment by abbradar** [comment]
(BTW, please cherry-pick my documentation fix)

**Comment by abbradar** [comment]
Oh, I see, you've already fixed that in https://github.com/NixOS/nixpkgs/pull/14372/commits/732ee7d6f16d9aa7551e6dc54d78eeae01fa655e -- good!

**Pull request closed without merging**
